import type { AnalysisProgress, CompleteAnalysisResult } from "./types"

export const mockJobs: AnalysisProgress[] = [
  {
    job_id: 1,
    url: "https://example.com",
    job_status: "completed",
    result_id: "result-001",
    analysis_status: "completed",
    progress: 1,
    analyzed_pages: 12,
    total_pages: 12,
  },
  {
    job_id: 2,
    url: "https://demo-store.com",
    job_status: "completed",
    result_id: "result-002",
    analysis_status: "completed",
    progress: 1,
    analyzed_pages: 8,
    total_pages: 8,
  },
  {
    job_id: 3,
    url: "https://my-blog.io",
    job_status: "processing",
    result_id: null,
    analysis_status: "crawling",
    progress: 0.45,
    analyzed_pages: 5,
    total_pages: 11,
  },
  {
    job_id: 4,
    url: "https://startup-landing.dev",
    job_status: "queued",
    result_id: null,
    analysis_status: null,
    progress: null,
    analyzed_pages: null,
    total_pages: null,
  },
]

export const mockResults: Record<number, CompleteAnalysisResult> = {
  1: {
    analysis: {
      id: "result-001",
      url: "https://example.com",
      status: "completed",
      progress: 100,
      total_pages: 12,
      analyzed_pages: 12,
      started_at: "2025-01-20T10:30:00Z",
      completed_at: "2025-01-20T10:35:42Z",
      sitemap_found: true,
      robots_txt_found: true,
      ssl_certificate: true,
      created_at: "2025-01-20T10:30:00Z",
    },
    summary: {
      analysis_id: "result-001",
      seo_score: 78,
      avg_load_time: 1.24,
      total_words: 15420,
      total_issues: 18,
    },
    pages: [
      {
        analysis_id: "result-001",
        url: "https://example.com/",
        title: "Example.com - Your Premium Domain Marketplace",
        meta_description: "Find and buy premium domains for your next project.",
        meta_keywords: "domains, premium, marketplace",
        canonical_url: "https://example.com/",
        h1_count: 1,
        h2_count: 4,
        h3_count: 8,
        word_count: 1850,
        image_count: 12,
        images_without_alt: 2,
        internal_links: 24,
        external_links: 5,
        load_time: 0.95,
        status_code: 200,
        content_size: 45200,
        mobile_friendly: true,
        has_structured_data: true,
        lighthouse_performance: 85,
        lighthouse_accessibility: 92,
        lighthouse_best_practices: 88,
        lighthouse_seo: 95,
      },
      {
        analysis_id: "result-001",
        url: "https://example.com/about",
        title: "About Us - Example.com",
        meta_description: "Learn more about our company and mission.",
        meta_keywords: "about, company, team",
        canonical_url: "https://example.com/about",
        h1_count: 1,
        h2_count: 3,
        h3_count: 5,
        word_count: 1200,
        image_count: 6,
        images_without_alt: 0,
        internal_links: 15,
        external_links: 2,
        load_time: 0.82,
        status_code: 200,
        content_size: 32100,
        mobile_friendly: true,
        has_structured_data: false,
        lighthouse_performance: 90,
        lighthouse_accessibility: 95,
        lighthouse_best_practices: 92,
        lighthouse_seo: 98,
      },
      {
        analysis_id: "result-001",
        url: "https://example.com/pricing",
        title: "Pricing - Example.com",
        meta_description: null,
        meta_keywords: null,
        canonical_url: "https://example.com/pricing",
        h1_count: 0,
        h2_count: 2,
        h3_count: 6,
        word_count: 890,
        image_count: 3,
        images_without_alt: 1,
        internal_links: 18,
        external_links: 0,
        load_time: 1.12,
        status_code: 200,
        content_size: 28500,
        mobile_friendly: true,
        has_structured_data: true,
        lighthouse_performance: 78,
        lighthouse_accessibility: 88,
        lighthouse_best_practices: 85,
        lighthouse_seo: 72,
      },
      {
        analysis_id: "result-001",
        url: "https://example.com/blog",
        title: "Blog - Latest News & Updates",
        meta_description: "Read our latest articles and industry insights.",
        meta_keywords: "blog, news, articles",
        canonical_url: "https://example.com/blog",
        h1_count: 1,
        h2_count: 8,
        h3_count: 12,
        word_count: 3200,
        image_count: 15,
        images_without_alt: 4,
        internal_links: 32,
        external_links: 8,
        load_time: 1.85,
        status_code: 200,
        content_size: 85600,
        mobile_friendly: true,
        has_structured_data: true,
        lighthouse_performance: 65,
        lighthouse_accessibility: 82,
        lighthouse_best_practices: 78,
        lighthouse_seo: 88,
      },
      {
        analysis_id: "result-001",
        url: "https://example.com/contact",
        title: "Contact Us",
        meta_description: "Get in touch with our support team.",
        meta_keywords: "contact, support, help",
        canonical_url: "https://example.com/contact",
        h1_count: 1,
        h2_count: 2,
        h3_count: 3,
        word_count: 450,
        image_count: 2,
        images_without_alt: 0,
        internal_links: 12,
        external_links: 3,
        load_time: 0.68,
        status_code: 200,
        content_size: 18200,
        mobile_friendly: true,
        has_structured_data: true,
        lighthouse_performance: 95,
        lighthouse_accessibility: 98,
        lighthouse_best_practices: 95,
        lighthouse_seo: 100,
      },
      {
        analysis_id: "result-001",
        url: "https://example.com/services",
        title: "Our Services",
        meta_description: "Explore our comprehensive range of services.",
        meta_keywords: null,
        canonical_url: "https://example.com/services",
        h1_count: 2,
        h2_count: 5,
        h3_count: 10,
        word_count: 2100,
        image_count: 8,
        images_without_alt: 1,
        internal_links: 20,
        external_links: 4,
        load_time: 1.35,
        status_code: 200,
        content_size: 52300,
        mobile_friendly: true,
        has_structured_data: false,
        lighthouse_performance: 72,
        lighthouse_accessibility: 85,
        lighthouse_best_practices: 80,
        lighthouse_seo: 82,
      },
    ],
    issues: [
      {
        page_id: "page-003",
        issue_type: "Critical",
        title: "Missing H1 Tag",
        description: "The page is missing an H1 heading tag, which is essential for SEO and accessibility.",
        page_url: "https://example.com/pricing",
        element: null,
        line_number: null,
        recommendation: "Add a single, descriptive H1 tag that includes your primary keyword for this page.",
      },
      {
        page_id: "page-003",
        issue_type: "Critical",
        title: "Missing Meta Description",
        description:
          "This page lacks a meta description, which can negatively impact click-through rates from search results.",
        page_url: "https://example.com/pricing",
        element: '<meta name="description">',
        line_number: 8,
        recommendation:
          "Add a compelling meta description between 150-160 characters that summarizes the page content.",
      },
      {
        page_id: "page-006",
        issue_type: "Critical",
        title: "Multiple H1 Tags",
        description: "This page has multiple H1 tags. Each page should have exactly one H1 tag.",
        page_url: "https://example.com/services",
        element: "<h1>",
        line_number: 45,
        recommendation: "Keep only one H1 tag per page and use H2-H6 for subheadings.",
      },
      {
        page_id: "page-001",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "Some images on this page are missing alt text, which affects accessibility and SEO.",
        page_url: "https://example.com/",
        element: "<img>",
        line_number: 124,
        recommendation: "Add descriptive alt text to all images that conveys their content or purpose.",
      },
      {
        page_id: "page-003",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "Some images on this page are missing alt text, which affects accessibility and SEO.",
        page_url: "https://example.com/pricing",
        element: "<img>",
        line_number: 89,
        recommendation: "Add descriptive alt text to all images that conveys their content or purpose.",
      },
      {
        page_id: "page-004",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "Some images on this page are missing alt text, which affects accessibility and SEO.",
        page_url: "https://example.com/blog",
        element: "<img>",
        line_number: 156,
        recommendation: "Add descriptive alt text to all images that conveys their content or purpose.",
      },
      {
        page_id: "page-006",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "Some images on this page are missing alt text, which affects accessibility and SEO.",
        page_url: "https://example.com/services",
        element: "<img>",
        line_number: 201,
        recommendation: "Add descriptive alt text to all images that conveys their content or purpose.",
      },
      {
        page_id: "page-004",
        issue_type: "Warning",
        title: "Slow Page Load Time",
        description: "This page takes longer than 1.5 seconds to load, which may affect user experience and rankings.",
        page_url: "https://example.com/blog",
        element: null,
        line_number: null,
        recommendation: "Optimize images, enable compression, minimize JavaScript, and consider using a CDN.",
      },
      {
        page_id: "page-002",
        issue_type: "Suggestion",
        title: "Missing Structured Data",
        description: "This page doesn't have structured data markup, which could enhance search result appearance.",
        page_url: "https://example.com/about",
        element: null,
        line_number: null,
        recommendation:
          "Add relevant Schema.org structured data (Organization, WebPage, etc.) to improve rich snippets.",
      },
      {
        page_id: "page-006",
        issue_type: "Suggestion",
        title: "Missing Structured Data",
        description: "This page doesn't have structured data markup, which could enhance search result appearance.",
        page_url: "https://example.com/services",
        element: null,
        line_number: null,
        recommendation:
          "Add relevant Schema.org structured data (Service, Organization, etc.) to improve rich snippets.",
      },
      {
        page_id: "page-001",
        issue_type: "Suggestion",
        title: "Consider Adding More Internal Links",
        description: "This page could benefit from additional internal links to improve site navigation and SEO.",
        page_url: "https://example.com/",
        element: null,
        line_number: null,
        recommendation:
          "Add relevant internal links to help users and search engines discover more content on your site.",
      },
      {
        page_id: "page-003",
        issue_type: "Suggestion",
        title: "Missing Meta Keywords",
        description: "While meta keywords have less SEO impact today, they can still help with organization.",
        page_url: "https://example.com/pricing",
        element: null,
        line_number: null,
        recommendation: "Consider adding relevant meta keywords for internal content organization purposes.",
      },
    ],
  },
  2: {
    analysis: {
      id: "result-002",
      url: "https://demo-store.com",
      status: "completed",
      progress: 100,
      total_pages: 8,
      analyzed_pages: 8,
      started_at: "2025-01-19T14:20:00Z",
      completed_at: "2025-01-19T14:24:15Z",
      sitemap_found: true,
      robots_txt_found: false,
      ssl_certificate: true,
      created_at: "2025-01-19T14:20:00Z",
    },
    summary: {
      analysis_id: "result-002",
      seo_score: 62,
      avg_load_time: 2.15,
      total_words: 8750,
      total_issues: 24,
    },
    pages: [
      {
        analysis_id: "result-002",
        url: "https://demo-store.com/",
        title: "Demo Store - Shop the Latest Products",
        meta_description: "Your one-stop shop for quality products at great prices.",
        meta_keywords: "shop, store, products, ecommerce",
        canonical_url: "https://demo-store.com/",
        h1_count: 1,
        h2_count: 6,
        h3_count: 12,
        word_count: 2200,
        image_count: 24,
        images_without_alt: 8,
        internal_links: 45,
        external_links: 3,
        load_time: 2.45,
        status_code: 200,
        content_size: 125000,
        mobile_friendly: false,
        has_structured_data: true,
        lighthouse_performance: 45,
        lighthouse_accessibility: 68,
        lighthouse_best_practices: 72,
        lighthouse_seo: 75,
      },
      {
        analysis_id: "result-002",
        url: "https://demo-store.com/products",
        title: "All Products",
        meta_description: null,
        meta_keywords: null,
        canonical_url: "https://demo-store.com/products",
        h1_count: 0,
        h2_count: 2,
        h3_count: 20,
        word_count: 1500,
        image_count: 30,
        images_without_alt: 12,
        internal_links: 50,
        external_links: 0,
        load_time: 3.2,
        status_code: 200,
        content_size: 180000,
        mobile_friendly: false,
        has_structured_data: false,
        lighthouse_performance: 32,
        lighthouse_accessibility: 55,
        lighthouse_best_practices: 65,
        lighthouse_seo: 58,
      },
      {
        analysis_id: "result-002",
        url: "https://demo-store.com/cart",
        title: "Shopping Cart - Demo Store",
        meta_description: "Review your cart and checkout.",
        meta_keywords: null,
        canonical_url: "https://demo-store.com/cart",
        h1_count: 1,
        h2_count: 1,
        h3_count: 2,
        word_count: 320,
        image_count: 0,
        images_without_alt: 0,
        internal_links: 8,
        external_links: 1,
        load_time: 0.95,
        status_code: 200,
        content_size: 15000,
        mobile_friendly: true,
        has_structured_data: false,
        lighthouse_performance: 88,
        lighthouse_accessibility: 92,
        lighthouse_best_practices: 90,
        lighthouse_seo: 85,
      },
    ],
    issues: [
      {
        page_id: "page-002",
        issue_type: "Critical",
        title: "Missing H1 Tag",
        description: "The page is missing an H1 heading tag.",
        page_url: "https://demo-store.com/products",
        element: null,
        line_number: null,
        recommendation: "Add a descriptive H1 tag to the page.",
      },
      {
        page_id: "page-002",
        issue_type: "Critical",
        title: "Missing Meta Description",
        description: "This page lacks a meta description.",
        page_url: "https://demo-store.com/products",
        element: null,
        line_number: null,
        recommendation: "Add a compelling meta description.",
      },
      {
        page_id: "page-001",
        issue_type: "Critical",
        title: "Not Mobile Friendly",
        description: "This page is not optimized for mobile devices.",
        page_url: "https://demo-store.com/",
        element: null,
        line_number: null,
        recommendation: "Implement responsive design and test on various mobile devices.",
      },
      {
        page_id: "page-002",
        issue_type: "Critical",
        title: "Not Mobile Friendly",
        description: "This page is not optimized for mobile devices.",
        page_url: "https://demo-store.com/products",
        element: null,
        line_number: null,
        recommendation: "Implement responsive design and test on various mobile devices.",
      },
      {
        page_id: "page-001",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "8 images are missing alt text.",
        page_url: "https://demo-store.com/",
        element: "<img>",
        line_number: null,
        recommendation: "Add descriptive alt text to all product images.",
      },
      {
        page_id: "page-002",
        issue_type: "Warning",
        title: "Images Missing Alt Text",
        description: "12 images are missing alt text.",
        page_url: "https://demo-store.com/products",
        element: "<img>",
        line_number: null,
        recommendation: "Add descriptive alt text to all product images.",
      },
      {
        page_id: "page-001",
        issue_type: "Warning",
        title: "Slow Page Load Time",
        description: "Page load time exceeds 2 seconds.",
        page_url: "https://demo-store.com/",
        element: null,
        line_number: null,
        recommendation: "Optimize images and enable lazy loading.",
      },
      {
        page_id: "page-002",
        issue_type: "Warning",
        title: "Slow Page Load Time",
        description: "Page load time exceeds 3 seconds.",
        page_url: "https://demo-store.com/products",
        element: null,
        line_number: null,
        recommendation: "Implement pagination and optimize images.",
      },
      {
        page_id: "page-002",
        issue_type: "Suggestion",
        title: "Missing Structured Data",
        description: "Consider adding Product structured data.",
        page_url: "https://demo-store.com/products",
        element: null,
        line_number: null,
        recommendation: "Add Schema.org Product markup for better search visibility.",
      },
    ],
  },
}
