// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

/**
 * Detailed analysis results
 */
export type AnalysisResults = { id: string, url: string, status: JobStatus, progress: number, total_pages: bigint, analyzed_pages: bigint, started_at: string | null, completed_at: string | null, sitemap_found: boolean, robots_txt_found: boolean, ssl_certificate: boolean, created_at: string, };
