// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analysis progress for frontend updates
 */
export type AnalysisProgress = { job_id: string, url: string, job_status: string, result_id: string | null, progress: number | null, analyzed_pages: bigint | null, total_pages: bigint | null, };
