// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisSettingsRequest = { max_pages: bigint, include_external_links: boolean, check_images: boolean, mobile_analysis: boolean, lighthouse_analysis: boolean, delay_between_requests: bigint, };
