// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

export type AnalysisJobResponse = { job_id: string, url: string, status: JobStatus, };
