// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of analysis results
 */
export type AnalysisSummary = { analysis_id: string, seo_score: bigint, avg_load_time: number, total_words: bigint, total_issues: bigint, };
