// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity level for SEO issues.
 */
export type IssueSeverity = "critical" | "warning" | "info";
