// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary statistics for a job (denormalized for fast dashboard access).
 */
export type JobSummary = { total_pages: bigint, pages_crawled: bigint, total_issues: bigint, critical_issues: bigint, warning_issues: bigint, info_issues: bigint, };
