// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lighthouse performance metrics for a page.
 */
export type LighthouseData = { page_id: string, performance_score: number | null, accessibility_score: number | null, best_practices_score: number | null, seo_score: number | null, first_contentful_paint_ms: number | null, largest_contentful_paint_ms: number | null, total_blocking_time_ms: number | null, cumulative_layout_shift: number | null, speed_index: number | null, time_to_interactive_ms: number | null, raw_json: string | null, };
