// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link details (frontend-compatible)
 */
export type LinkDetail = { url: string, text: string, is_external: boolean, is_broken: boolean, status_code: bigint | null, };
