// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadingElement } from "./HeadingElement";
import type { ImageElement } from "./ImageElement";
import type { JsonValue } from "./serde_json/JsonValue";
import type { LinkDetail } from "./LinkDetail";

/**
 * Page analysis data (frontend-compatible format)
 */
export type PageAnalysisData = { analysis_id: string, url: string, title: string | null, meta_description: string | null, meta_keywords: string | null, canonical_url: string | null, h1_count: bigint, h2_count: bigint, h3_count: bigint, word_count: bigint, image_count: bigint, images_without_alt: bigint, internal_links: bigint, external_links: bigint, load_time: number, status_code: bigint | null, content_size: bigint, mobile_friendly: boolean, has_structured_data: boolean, lighthouse_performance: number | null, lighthouse_accessibility: number | null, lighthouse_best_practices: number | null, lighthouse_seo: number | null, lighthouse_seo_audits: JsonValue | null, lighthouse_performance_metrics: JsonValue | null, links: Array<string>, headings: Array<HeadingElement>, images: Array<ImageElement>, detailed_links: Array<LinkDetail>, };
