// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource status (robots.txt, sitemap, SSL)
 */
export type ResourceStatus = "not_checked" | { "found": string } | "not_found" | { "unauthorized": string } | "error";
