// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

/**
 * SEO issue (frontend-compatible format)
 */
export type SeoIssue = { page_id: string, severity: IssueSeverity, title: string, description: string, page_url: string, element: string | null, recommendation: string, line_number: number | null, };
