//! Issue Rule System
//!
//! This module defines the trait and implementations for issue rules.
//! Issue rules are evaluated against pages to generate SEO issues.

use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::contexts::{IssueSeverity, NewIssue, Page};

/// Information about an issue rule for the frontend
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct IssueRuleInfo {
    pub id: String,
    pub name: String,
    pub category: String,
    pub severity: String,
    pub rule_type: String,
    pub target_field: Option<String>,
    pub recommendation: Option<String>,
    pub is_builtin: bool,
    pub is_enabled: bool,
}

/// Context provided to rules during evaluation
#[derive(Debug, Clone, Default)]
pub struct EvaluationContext {
    /// Raw HTML content of the page
    pub html: Option<String>,

    /// HTTP response headers
    pub headers: HashMap<String, String>,

    /// Lighthouse data if available
    pub lighthouse_data: Option<crate::contexts::LighthouseData>,

    /// Additional extracted data
    pub extracted_data: HashMap<String, serde_json::Value>,
}

impl EvaluationContext {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_html(mut self, html: String) -> Self {
        self.html = Some(html);
        self
    }

    pub fn with_headers(mut self, headers: HashMap<String, String>) -> Self {
        self.headers = headers;
        self
    }
}

/// Types of rules that can be evaluated
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleType {
    /// Check if a field exists/is not empty
    Presence,

    /// Check if a numeric value is within a range
    Threshold,

    /// Check if a field matches a regex pattern
    Regex,

    /// Check if a field equals a specific value
    Equals,

    /// Check string length constraints
    Length,

    /// Custom rule with complex logic
    Custom,
}

/// Condition definition for rules
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct RuleCondition {
    /// Type of condition
    #[serde(rename = "type")]
    pub condition_type: String,

    /// Negate the result
    #[serde(default)]
    pub negate: bool,

    /// Minimum value (for threshold/length rules)
    pub min: Option<f64>,

    /// Maximum value (for threshold/length rules)
    pub max: Option<f64>,

    /// Exact value to match
    pub value: Option<String>,

    /// Regex pattern
    pub pattern: Option<String>,

    /// Regex flags
    pub flags: Option<String>,
}

impl RuleCondition {
    /// Create a presence condition (check if field exists)
    pub fn presence(negate: bool) -> Self {
        Self {
            condition_type: "presence".to_string(),
            negate,
            min: None,
            max: None,
            value: None,
            pattern: None,
            flags: None,
        }
    }

    /// Create a length condition
    pub fn length(min: Option<f64>, max: Option<f64>) -> Self {
        Self {
            condition_type: "length".to_string(),
            negate: false,
            min,
            max,
            value: None,
            pattern: None,
            flags: None,
        }
    }

    /// Create a threshold condition for numeric values
    pub fn threshold(min: Option<f64>, max: Option<f64>) -> Self {
        Self {
            condition_type: "threshold".to_string(),
            negate: false,
            min,
            max,
            value: None,
            pattern: None,
            flags: None,
        }
    }

    /// Create a regex condition
    pub fn regex(pattern: &str, flags: Option<&str>) -> Self {
        Self {
            condition_type: "regex".to_string(),
            negate: false,
            min: None,
            max: None,
            value: None,
            pattern: Some(pattern.to_string()),
            flags: flags.map(|s| s.to_string()),
        }
    }

    /// Create an equals condition
    pub fn equals(value: &str) -> Self {
        Self {
            condition_type: "equals".to_string(),
            negate: false,
            min: None,
            max: None,
            value: Some(value.to_string()),
            pattern: None,
            flags: None,
        }
    }
}

/// Trait for issue rules
pub trait IssueRule: Send + Sync {
    /// Unique identifier for this rule
    fn id(&self) -> &str;

    /// Human-readable name
    fn name(&self) -> &str;

    /// Category for grouping (seo, performance, accessibility)
    fn category(&self) -> &str;

    /// Severity of issues generated by this rule
    fn severity(&self) -> IssueSeverity;

    /// Evaluate the rule against a page (synchronous for thread safety)
    fn evaluate(&self, page: &Page, context: &EvaluationContext) -> Option<NewIssue>;

    /// Whether this rule applies to the given page
    fn applies_to(&self, _page: &Page) -> bool {
        true
    }

    /// Get the recommendation for fixing this issue
    fn recommendation(&self) -> Option<&str> {
        None
    }
}

/// Rule that checks if a field exists/is not empty
pub struct PresenceRule {
    pub id: String,
    pub name: String,
    pub category: String,
    pub severity: IssueSeverity,
    pub field: String,
    pub must_exist: bool,
    pub message: String,
    pub recommendation: Option<String>,
}

impl PresenceRule {
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        field: impl Into<String>,
        must_exist: bool,
        severity: IssueSeverity,
    ) -> Self {
        let field_name = field.into();
        let message = if must_exist {
            format!("{} is missing", field_name)
        } else {
            format!("{} should not be present", field_name)
        };

        Self {
            id: id.into(),
            name: name.into(),
            category: "seo".to_string(),
            severity,
            field: field_name,
            must_exist,
            message,
            recommendation: None,
        }
    }

    fn get_field_value(&self, page: &Page) -> Option<String> {
        match self.field.as_str() {
            "title" => page.title.clone(),
            "meta_description" => page.meta_description.clone(),
            "canonical_url" => page.canonical_url.clone(),
            "robots_meta" => page.robots_meta.clone(),
            "content_type" => page.content_type.clone(),
            _ => None,
        }
    }
}

impl IssueRule for PresenceRule {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn category(&self) -> &str {
        &self.category
    }

    fn severity(&self) -> IssueSeverity {
        self.severity
    }

    fn evaluate(&self, page: &Page, _context: &EvaluationContext) -> Option<NewIssue> {
        let value = self.get_field_value(page);
        let exists = value.is_some() && !value.as_ref().is_some_and(|v| v.is_empty());

        let should_create_issue = if self.must_exist {
            !exists // Issue if should exist but doesn't
        } else {
            exists // Issue if shouldn't exist but does
        };

        if should_create_issue {
            Some(NewIssue {
                job_id: page.job_id.clone(),
                page_id: Some(page.id.clone()),
                issue_type: self.name.clone(),
                severity: self.severity,
                message: self.message.clone(),
                details: self.recommendation.clone(),
            })
        } else {
            None
        }
    }

    fn recommendation(&self) -> Option<&str> {
        self.recommendation.as_deref()
    }
}

/// Rule that checks numeric thresholds
pub struct ThresholdRule {
    pub id: String,
    pub name: String,
    pub category: String,
    pub severity: IssueSeverity,
    pub field: String,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub message_template: String,
    pub recommendation: Option<String>,
}

impl ThresholdRule {
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        field: impl Into<String>,
        severity: IssueSeverity,
    ) -> Self {
        let field_str = field.into();
        Self {
            id: id.into(),
            name: name.into(),
            category: "seo".to_string(),
            severity,
            field: field_str.clone(),
            min: None,
            max: None,
            message_template: format!("{} is outside acceptable range", field_str),
            recommendation: None,
        }
    }

    pub fn with_min(mut self, min: f64) -> Self {
        self.min = Some(min);
        self
    }

    pub fn with_max(mut self, max: f64) -> Self {
        self.max = Some(max);
        self
    }

    pub fn with_range(mut self, min: f64, max: f64) -> Self {
        self.min = Some(min);
        self.max = Some(max);
        self
    }

    pub fn with_recommendation(mut self, recommendation: impl Into<String>) -> Self {
        self.recommendation = Some(recommendation.into());
        self
    }

    fn get_field_value(&self, page: &Page) -> Option<f64> {
        match self.field.as_str() {
            "word_count" => page.word_count.map(|v| v as f64),
            "load_time_ms" => page.load_time_ms.map(|v| v as f64),
            "response_size_bytes" => page.response_size_bytes.map(|v| v as f64),
            "status_code" => page.status_code.map(|v| v as f64),
            "depth" => Some(page.depth as f64),
            _ => None,
        }
    }
}

impl IssueRule for ThresholdRule {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn category(&self) -> &str {
        &self.category
    }

    fn severity(&self) -> IssueSeverity {
        self.severity
    }

    fn evaluate(&self, page: &Page, _context: &EvaluationContext) -> Option<NewIssue> {
        let value = self.get_field_value(page)?;

        let below_min = self.min.is_some_and(|min| value < min);
        let above_max = self.max.is_some_and(|max| value > max);

        if below_min || above_max {
            let message = match (below_min, above_max) {
                (true, false) => format!(
                    "{} ({}) is below minimum ({})",
                    self.field,
                    value,
                    self.min.unwrap()
                ),
                (false, true) => format!(
                    "{} ({}) is above maximum ({})",
                    self.field,
                    value,
                    self.max.unwrap()
                ),
                _ => format!(
                    "{} ({}) is outside range ({:?})",
                    self.field,
                    value,
                    (self.min, self.max)
                ),
            };

            Some(NewIssue {
                job_id: page.job_id.clone(),
                page_id: Some(page.id.clone()),
                issue_type: self.name.clone(),
                severity: self.severity,
                message,
                details: self.recommendation.clone(),
            })
        } else {
            None
        }
    }

    fn recommendation(&self) -> Option<&str> {
        self.recommendation.as_deref()
    }
}

/// Rule that checks string length constraints
pub struct LengthRule {
    pub id: String,
    pub name: String,
    pub category: String,
    pub severity: IssueSeverity,
    pub field: String,
    pub min: Option<usize>,
    pub max: Option<usize>,
    pub message_template: String,
    pub recommendation: Option<String>,
}

impl LengthRule {
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        field: impl Into<String>,
        severity: IssueSeverity,
    ) -> Self {
        let field_str = field.into();
        Self {
            id: id.into(),
            name: name.into(),
            category: "seo".to_string(),
            severity,
            field: field_str.clone(),
            min: None,
            max: None,
            message_template: format!("{} has invalid length", field_str),
            recommendation: None,
        }
    }

    pub fn with_min(mut self, min: usize) -> Self {
        self.min = Some(min);
        self
    }

    pub fn with_max(mut self, max: usize) -> Self {
        self.max = Some(max);
        self
    }

    pub fn with_range(mut self, min: usize, max: usize) -> Self {
        self.min = Some(min);
        self.max = Some(max);
        self
    }

    pub fn with_recommendation(mut self, recommendation: impl Into<String>) -> Self {
        self.recommendation = Some(recommendation.into());
        self
    }

    fn get_field_value(&self, page: &Page) -> Option<String> {
        match self.field.as_str() {
            "title" => page.title.clone(),
            "meta_description" => page.meta_description.clone(),
            "canonical_url" => page.canonical_url.clone(),
            _ => None,
        }
    }
}

impl IssueRule for LengthRule {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn category(&self) -> &str {
        &self.category
    }

    fn severity(&self) -> IssueSeverity {
        self.severity
    }

    fn evaluate(&self, page: &Page, _context: &EvaluationContext) -> Option<NewIssue> {
        let value = self.get_field_value(page)?;
        let len = value.len();

        let below_min = self.min.is_some_and(|min| len < min);
        let above_max = self.max.is_some_and(|max| len > max);

        if below_min || above_max {
            let message = match (below_min, above_max) {
                (true, false) => format!(
                    "{} is too short ({} chars, recommend {}-{})",
                    self.field,
                    len,
                    self.min.unwrap(),
                    self.max.unwrap_or(usize::MAX)
                ),
                (false, true) => format!(
                    "{} is too long ({} chars, recommend {}-{})",
                    self.field,
                    len,
                    self.min.unwrap_or(0),
                    self.max.unwrap()
                ),
                _ => format!("{} length ({}) is outside recommended range", self.field, len),
            };

            Some(NewIssue {
                job_id: page.job_id.clone(),
                page_id: Some(page.id.clone()),
                issue_type: self.name.clone(),
                severity: self.severity,
                message,
                details: self.recommendation.clone(),
            })
        } else {
            None
        }
    }

    fn recommendation(&self) -> Option<&str> {
        self.recommendation.as_deref()
    }
}

/// Rule that checks regex patterns
pub struct RegexRule {
    pub id: String,
    pub name: String,
    pub category: String,
    pub severity: IssueSeverity,
    pub field: String,
    pub pattern: Regex,
    pub should_match: bool,
    pub message: String,
    pub recommendation: Option<String>,
}

impl RegexRule {
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        field: impl Into<String>,
        pattern: &str,
        should_match: bool,
        severity: IssueSeverity,
    ) -> Result<Self, regex::Error> {
        let pattern = Regex::new(pattern)?;
        let field_name = field.into();
        let message = if should_match {
            format!("{} does not match required pattern", field_name)
        } else {
            format!("{} matches a disallowed pattern", field_name)
        };

        Ok(Self {
            id: id.into(),
            name: name.into(),
            category: "seo".to_string(),
            severity,
            field: field_name,
            pattern,
            should_match,
            message,
            recommendation: None,
        })
    }

    pub fn with_recommendation(mut self, recommendation: impl Into<String>) -> Self {
        self.recommendation = Some(recommendation.into());
        self
    }

    fn get_field_value(&self, page: &Page) -> Option<String> {
        match self.field.as_str() {
            "title" => page.title.clone(),
            "meta_description" => page.meta_description.clone(),
            "canonical_url" => page.canonical_url.clone(),
            "url" => Some(page.url.clone()),
            _ => None,
        }
    }
}

impl IssueRule for RegexRule {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn category(&self) -> &str {
        &self.category
    }

    fn severity(&self) -> IssueSeverity {
        self.severity
    }

    fn evaluate(&self, page: &Page, _context: &EvaluationContext) -> Option<NewIssue> {
        let value = self.get_field_value(page)?;
        let matches = self.pattern.is_match(&value);

        let should_create_issue = if self.should_match {
            !matches // Issue if should match but doesn't
        } else {
            matches // Issue if shouldn't match but does
        };

        if should_create_issue {
            Some(NewIssue {
                job_id: page.job_id.clone(),
                page_id: Some(page.id.clone()),
                issue_type: self.name.clone(),
                severity: self.severity,
                message: self.message.clone(),
                details: self.recommendation.clone(),
            })
        } else {
            None
        }
    }

    fn recommendation(&self) -> Option<&str> {
        self.recommendation.as_deref()
    }
}

/// Rule that checks for HTTP status codes
pub struct StatusCodeRule {
    pub id: String,
    pub name: String,
    pub severity: IssueSeverity,
    pub error_codes: Vec<u16>,
    pub recommendation: Option<String>,
}

impl StatusCodeRule {
    pub fn new(id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            severity: IssueSeverity::Critical,
            error_codes: vec![400, 401, 403, 404, 500, 502, 503, 504],
            recommendation: None,
        }
    }

    pub fn with_codes(mut self, codes: Vec<u16>) -> Self {
        self.error_codes = codes;
        self
    }
}

impl IssueRule for StatusCodeRule {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn category(&self) -> &str {
        "seo"
    }

    fn severity(&self) -> IssueSeverity {
        self.severity
    }

    fn evaluate(&self, page: &Page, _context: &EvaluationContext) -> Option<NewIssue> {
        let status = page.status_code?;

        if self.error_codes.contains(&(status as u16)) {
            Some(NewIssue {
                job_id: page.job_id.clone(),
                page_id: Some(page.id.clone()),
                issue_type: self.name.clone(),
                severity: self.severity,
                message: format!("Page returned HTTP status code {}", status),
                details: self.recommendation.clone(),
            })
        } else {
            None
        }
    }

    fn recommendation(&self) -> Option<&str> {
        self.recommendation.as_deref()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn make_page(overrides: impl FnOnce(&mut Page)) -> Page {
        let mut page = Page {
            id: "test-page".to_string(),
            job_id: "test-job".to_string(),
            url: "https://example.com".to_string(),
            depth: 0,
            status_code: Some(200),
            content_type: Some("text/html".to_string()),
            title: Some("Test Title".to_string()),
            meta_description: Some("Test description".to_string()),
            canonical_url: None,
            robots_meta: None,
            word_count: Some(100),
            load_time_ms: Some(1000),
            response_size_bytes: Some(512),
            has_viewport: true,
            has_structured_data: false,
            crawled_at: Utc::now(),
            extracted_data: std::collections::HashMap::new(),
        };
        overrides(&mut page);
        page
    }

    #[test]
    fn test_presence_rule_missing_title() {
        let rule = PresenceRule::new(
            "missing-title",
            "Missing Title",
            "title",
            true,
            IssueSeverity::Critical,
        );

        let page = make_page(|p| p.title = None);
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_some());
        let issue = issue.unwrap();
        assert_eq!(issue.issue_type, "Missing Title");
        assert_eq!(issue.severity, IssueSeverity::Critical);
    }

    #[test]
    fn test_presence_rule_has_title() {
        let rule = PresenceRule::new(
            "missing-title",
            "Missing Title",
            "title",
            true,
            IssueSeverity::Critical,
        );

        let page = make_page(|p| {});
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_none());
    }

    #[test]
    fn test_length_rule_title_too_short() {
        let rule = LengthRule::new(
            "title-length",
            "Title Length",
            "title",
            IssueSeverity::Warning,
        )
        .with_range(30, 60);

        let page = make_page(|p| p.title = Some("Short".to_string()));
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_some());
        assert!(issue.unwrap().message.contains("too short"));
    }

    #[test]
    fn test_length_rule_title_too_long() {
        let rule = LengthRule::new(
            "title-length",
            "Title Length",
            "title",
            IssueSeverity::Warning,
        )
        .with_range(30, 60);

        let page = make_page(|p| {
            p.title = Some("This is a very long title that exceeds the maximum recommended length".to_string())
        });
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_some());
        assert!(issue.unwrap().message.contains("too long"));
    }

    #[test]
    fn test_threshold_rule_word_count() {
        let rule = ThresholdRule::new(
            "low-word-count",
            "Low Word Count",
            "word_count",
            IssueSeverity::Info,
        )
        .with_min(300.0);

        let page = make_page(|p| p.word_count = Some(100));
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_some());
    }

    #[test]
    fn test_status_code_rule() {
        let rule = StatusCodeRule::new("http-error", "HTTP Error");

        let page = make_page(|p| p.status_code = Some(404));
        let context = EvaluationContext::new();

        let issue = rule.evaluate(&page, &context);
        assert!(issue.is_some());
        assert!(issue.unwrap().message.contains("404"));
    }
}
