// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisResults } from "./AnalysisResults";
import type { AnalysisSummary } from "./AnalysisSummary";
import type { PageAnalysisData } from "./PageAnalysisData";
import type { SeoIssue } from "./SeoIssue";

/**
 * Complete analysis result (frontend-compatible format)
 */
export type CompleteAnalysisResult = { analysis: AnalysisResults, pages: Array<PageAnalysisData>, issues: Array<SeoIssue>, summary: AnalysisSummary, };
