// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Heading element for frontend display.
 */
export type HeadingElement = { tag: string, text: string, };
