// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image element for frontend display.
 */
export type ImageElement = { src: string, alt: string | null, };
