// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of link (internal, external, resource).
 */
export type LinkType = "internal" | "external" | "resource";
