
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGeminiInsights(request: GeminiRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_insights", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiApiKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiApiKey(apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_api_key", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiPersona() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_persona") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiPersona(persona: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_persona", { persona }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiRequirements() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_requirements") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiRequirements(requirements: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_requirements", { requirements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiContextOptions() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_context_options") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiContextOptions(options: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_context_options", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiPromptBlocks() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_prompt_blocks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiPromptBlocks(blocks: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_prompt_blocks", { blocks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeminiEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gemini_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAnalysis(url: string, settings: AnalysisSettingsRequest | null) : Promise<Result<AnalysisJobResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_analysis", { url, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalysisProgress(jobId: string) : Promise<Result<AnalysisProgress, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analysis_progress", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllJobs(limit: number | null, offset: number | null) : Promise<Result<AnalysisProgress[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_jobs", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPaginatedJobs(limit: number, offset: number, urlFilter: string | null, statusFilter: string | null) : Promise<Result<PaginatedJobsResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_paginated_jobs", { limit, offset, urlFilter, statusFilter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAnalysis(jobId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_analysis", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getResult(jobId: string) : Promise<Result<CompleteAnalysisResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_result", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalysisDefaults() : Promise<Result<AnalysisSettingsRequest, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analysis_defaults") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFreeTierDefaults() : Promise<Result<AnalysisSettingsRequest, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_free_tier_defaults") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateLicense(licenseKey: string) : Promise<Result<Policy, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_license", { licenseKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateWithKey(key: string) : Promise<Result<Policy, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_with_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUserPolicy() : Promise<Result<Policy, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user_policy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLicenseTier() : Promise<Result<LicenseTier, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_license_tier") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMachineId() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_machine_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCustomChecks() : Promise<Result<CustomCheck[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_custom_checks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCustomCheck(params: CustomCheckParams) : Promise<Result<CustomCheck, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_custom_check", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomCheck(id: string, params: CustomCheckParams) : Promise<Result<CustomCheck, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_check", { id, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomCheck(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_check", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCustomExtractors() : Promise<Result<CustomExtractor[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_custom_extractors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCustomExtractor(params: CustomExtractorParams) : Promise<Result<CustomExtractor, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_custom_extractor", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomExtractor(id: string, params: CustomExtractorParams) : Promise<Result<CustomExtractor, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_extractor", { id, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomExtractor(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_extractor", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
progressEvent: ProgressEvent
}>({
progressEvent: "progress-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AnalysisJobResponse = { job_id: string; url: string; status: JobStatus }
/**
 * Analysis progress for frontend updates
 */
export type AnalysisProgress = { job_id: string; url: string; job_status: JobStatus; result_id: string | null; progress: number | null; max_pages: number | null; is_deep_audit: boolean | null; total_issues: number | null }
export type AnalysisResults = { id: string; url: string; status: JobStatus; progress: number; total_pages: number; analyzed_pages: number; started_at: string | null; completed_at: string | null; sitemap_found: boolean; robots_txt_found: boolean; ssl_certificate: boolean; created_at: string }
export type AnalysisSettingsRequest = { max_pages: number; include_subdomains: boolean; check_images: boolean; mobile_analysis: boolean; lighthouse_analysis: boolean; delay_between_requests: number }
export type AnalysisSummary = { analysis_id: string; seo_score: number; avg_load_time: number; total_words: number; total_issues: number }
/**
 * Wrapper for errors returned from Tauri commands.
 * This type is serializable and can be sent to the frontend.
 */
export type CommandError = string
export type CompleteAnalysisResponse = { analysis: AnalysisResults; pages: PageAnalysisData[]; issues: SeoIssue[]; summary: AnalysisSummary }
/**
 * A user-defined check that inspects extracted page data and produces an issue.
 */
export type CustomCheck = { id: string; name: string; severity: IssueSeverity; 
/**
 * The extracted_data key (or built-in page field) to evaluate.
 */
field: string; operator: Operator; 
/**
 * Threshold value for numeric/text comparisons; unused for `Missing`.
 */
threshold: string | null; 
/**
 * Template for the issue message. `{value}` is replaced with the actual field value.
 */
message_template: string; enabled: boolean }
/**
 * Parameters for creating or updating a custom check.
 */
export type CustomCheckParams = { name: string; severity: IssueSeverity; field: string; operator: Operator; threshold: string | null; message_template: string; enabled: boolean }
/**
 * A user-defined CSS-selector extractor that populates extracted_data.
 */
export type CustomExtractor = { id: string; name: string; 
/**
 * Key written into `page.extracted_data`.
 */
key: string; selector: string; attribute: string | null; multiple: boolean; enabled: boolean }
/**
 * Parameters for creating or updating a custom extractor.
 */
export type CustomExtractorParams = { name: string; key: string; selector: string; attribute: string | null; multiple: boolean; enabled: boolean }
export type Feature = "LinkAnalysis" | "GraphView" | "ExportReports"
export type GeminiRequest = { analysis_id: string; url: string; seo_score: number; pages_count: number; total_issues: number; critical_issues: number; warning_issues: number; suggestion_issues: number; top_issues: string[]; avg_load_time: number; total_words: number; ssl_certificate: boolean; sitemap_found: boolean; robots_txt_found: boolean }
export type HeadingElement = { tag: string; text: string }
export type ImageElement = { src: string; alt: string | null }
export type IssueSeverity = "critical" | "warning" | "info"
/**
 * Status of an SEO analysis job.
 */
export type JobStatus = "pending" | "discovery" | "processing" | "completed" | "failed" | "cancelled"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LicenseTier = "Free" | "Premium"
export type LinkDetail = { href: string; text: string; link_type: LinkType; is_broken: boolean; status_code: number | null }
export type LinkType = "internal" | "subdomain" | "external" | "resource"
/**
 * Condition operator for a custom check.
 */
export type Operator = "missing" | "lt" | "gt" | "contains" | "not_contains"
export type PageAnalysisData = { analysis_id: string; url: string; title: string | null; meta_description: string | null; meta_keywords: string | null; canonical_url: string | null; word_count: number; image_count: number; images_without_alt: number; internal_links: number; external_links: number; load_time: number; status_code: number | null; content_size: number; mobile_friendly: boolean; has_structured_data: boolean; lighthouse_performance: number | null; lighthouse_accessibility: number | null; lighthouse_best_practices: number | null; lighthouse_seo: number | null; lighthouse_seo_audits: JsonValue | null; lighthouse_performance_metrics: JsonValue | null; images: ImageElement[]; detailed_links: LinkDetail[]; headings: HeadingElement[]; 
/**
 * Extracted data from custom extractors (key-value pairs)
 */
extracted_data: Partial<{ [key in string]: JsonValue }> }
export type PaginatedJobsResponse = { items: AnalysisProgress[]; total: number }
export type Policy = { tier: LicenseTier; max_pages: number; enabled_features: Feature[]; 
/**
 * True when the installed build is newer than the license's update window.
 * The app still works — this flag drives a renewal banner in the UI.
 */
updates_expired: boolean }
export type ProgressEvent = { event: "analysis"; job_id: string; progress: number; pages_analyzed: number; total_pages: number } | { event: "discovery"; job_id: string; count: number; total_pages: number }
export type SeoIssue = { page_id: string; severity: IssueSeverity; title: string; description: string; page_url: string; element: string | null; recommendation: string; line_number: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
