/**
 * Extension System Types for Frontend
 *
 * These types correspond to the backend extension system in src-tauri/src/extension/
 * and the commands in src-tauri/src/commands/extension.rs
 */

// ============================================================================
// Issue Rule Types
// ============================================================================

/**
 * Rule type determines how the rule evaluates conditions
 */
export type RuleType =
  | "presence" // Check if a field exists or has content
  | "threshold" // Check if a numeric value is within bounds
  | "regex" // Check if a field matches a pattern
  | "custom"; // Custom evaluation logic

/**
 * Severity level for issues generated by rules
 */
export type RuleSeverity = "critical" | "warning" | "info";

/**
 * Information about an issue rule for display in the UI
 */
export interface IssueRuleInfo {
  /** Unique identifier for the rule */
  id: string;
  /** Human-readable name */
  name: string;
  /** Category (e.g., "seo", "accessibility", "performance") */
  category: string;
  /** Severity level */
  severity: RuleSeverity;
  /** Type of rule evaluation */
  rule_type: RuleType;
  /** The field this rule targets */
  target_field: string | null;
  /** Recommendation for fixing the issue */
  recommendation: string | null;
  /** Whether this is a built-in rule */
  is_builtin: boolean;
  /** Whether this rule is currently enabled */
  is_enabled: boolean;
}

/**
 * Request to create a new custom rule
 */
export interface CreateRuleRequest {
  name: string;
  category: string;
  severity: RuleSeverity;
  rule_type: RuleType;
  target_field: string;
  threshold_min?: number;
  threshold_max?: number;
  regex_pattern?: string;
  recommendation?: string;
}

/**
 * Request to update an existing rule
 */
export interface UpdateRuleRequest {
  id: string;
  name?: string;
  severity?: RuleSeverity;
  threshold_min?: number;
  threshold_max?: number;
  regex_pattern?: string;
  recommendation?: string;
  is_enabled?: boolean;
}

// ============================================================================
// Data Extractor Types
// ============================================================================

/**
 * Type of data extraction method
 */
export type ExtractorType =
  | "css_selector" // Extract using CSS selectors
  | "xpath" // Extract using XPath
  | "regex" // Extract using regular expressions
  | "json_path" // Extract from JSON using JSONPath
  | "custom"; // Custom extraction logic

/**
 * Information about a data extractor
 */
export interface DataExtractorInfo {
  /** Unique identifier for the extractor */
  id: string;
  /** Human-readable name */
  name: string;
  /** Description of what this extractor does */
  description: string | null;
  /** Type of extraction method */
  extractor_type: ExtractorType;
  /** Whether this is a built-in extractor */
  is_builtin: boolean;
  /** Whether this extractor is currently enabled */
  is_enabled: boolean;
}

/**
 * Request to create a new data extractor
 */
export interface CreateExtractorRequest {
  name: string;
  description?: string;
  extractor_type: ExtractorType;
  selector: string; // CSS selector, XPath, or regex pattern
  target_field: string; // Field name to store extracted data
  is_multiple?: boolean; // Whether to extract multiple values
  attribute?: string; // Attribute to extract (for CSS selectors)
}

// ============================================================================
// Audit Check Types
// ============================================================================

/**
 * Information about an audit check
 */
export interface AuditCheckInfo {
  /** Unique key for the check */
  key: string;
  /** Human-readable label */
  label: string;
  /** Category this check belongs to */
  category: string;
  /** Weight for scoring calculation */
  weight: number;
  /** Whether this is a built-in check */
  is_builtin: boolean;
  /** Whether this check is currently enabled */
  is_enabled: boolean;
}

/**
 * Request to create a new audit check
 */
export interface CreateAuditCheckRequest {
  key: string;
  label: string;
  category: string;
  weight: number;
  description?: string;
  check_logic: string; // JSON or DSL describing the check logic
}

// ============================================================================
// Extension System Summary
// ============================================================================

/**
 * Summary of the extension system status
 */
export interface ExtensionSummary {
  /** Total number of issue rules */
  total_rules: number;
  /** Total number of data extractors */
  total_extractors: number;
  /** Total number of audit checks */
  total_checks: number;
  /** Number of built-in rules */
  builtin_rules: number;
  /** Number of custom rules */
  custom_rules: number;
}

// ============================================================================
// Category and Filter Types
// ============================================================================

/**
 * Predefined categories for rules and checks
 */
export const EXTENSION_CATEGORIES = [
  "seo",
  "accessibility",
  "performance",
  "security",
  "content",
  "technical",
  "ux",
  "mobile",
] as const;

export type ExtensionCategory = (typeof EXTENSION_CATEGORIES)[number];

/**
 * Filter options for extension lists
 */
export interface ExtensionFilter {
  category?: ExtensionCategory;
  severity?: RuleSeverity;
  is_builtin?: boolean;
  is_enabled?: boolean;
  search?: string;
}

// ============================================================================
// UI State Types
// ============================================================================

/**
 * Tab options for the extension management UI
 */
export type ExtensionTab = "rules" | "extractors" | "checks";

/**
 * State for extension management page
 */
export interface ExtensionState {
  summary: ExtensionSummary | null;
  rules: IssueRuleInfo[];
  extractors: DataExtractorInfo[];
  checks: AuditCheckInfo[];
  isLoading: boolean;
  error: string | null;
}
